### ISSUE TITLE
xcode7.3 swift project pod error~~!!

### ISSUE THREAD

**Issue by danwey** [inspace-io/INSPhotoGallery#1]
'INSPhoto' cannot be constructed because it has no accessible initializers
please help me~!!

**Comment by m1entus** [comment]
Thanks, fixed

**Comment by ghost** [comment]
The Source code fixed it, but the code from pod install is still error, please fix it.

**Comment by m1entus** [comment]
Please clean delivery data and make sure you have 1.0.1, i had same issue with sample project.

**Comment by ghost** [comment]
When I remove Pods folder in example, and change Podfile pod 'INSPhotoGallery', :podspec => '../INSPhotoGallery.podspec' to Pod 'INSPhtoGallery', and then run pod install, the problem will appear. I don't know why.

**Comment by m1entus** [comment]
Yeah, i updated file from Pod rather than SourceCode, now it is fixed in 1.0.2. Now Fixed :)
