### ISSUE TITLE
If the StatusBar is set to Light the share and close buttons are not displaying well

### ISSUE THREAD

**Issue by jarrillaga** [inspace-io/INSPhotoGallery#13]
Hi, thanks for your control. I´m using it on my app which has a black navigation bar so the status bar must be set to light. In order to do this, in the info.plist you have to add the property View controller-based status bar appearance = NO and in the appDelegate         UIApplication.shared.statusBarStyle = .lightContent.

If you do these settings, the status bar font will be white and you will reproduce the issue. Having white fonts in the status bar is a very common task. 

I would appreciate if you can help me with this.

**Comment by zurce** [comment]
Can be easily fixed with 

```
      var recto = galleryPreview.overlayView.view().frame;
            recto.origin.y = 20;
            galleryPreview.overlayView.view().frame = recto;
```

Before you present your INSPhotosViewController
