### ISSUE TITLE
Cannot view https image

### ISSUE THREAD

**Issue by saravananNV** [inspace-io/INSPhotoGallery#3]
Hi developers,

```
 we are integrating box (a cloud sharing server) with our ios app.the images from box.com are coming response as https . when we try to show the https images it throws error.
```

**Comment by m1entus** [comment]
Which error?

**Comment by saravananNV** [comment]
we got Status code error 402  io.haneke

**Comment by m1entus** [comment]
This is not a problem of this library. 402 Payment Required
Reserved for future use. The original intention was that this code might be used as part of some form of digital cash or micropayment scheme, but that has not happened, and this code is not usually used. Google Developers API uses this status if a particular developer has exceeded the daily limit on requests.[38]
