### ISSUE TITLE
Version 1.2 is crashing in Xcode 9 using swift 3.2

### ISSUE THREAD

**Issue by lucasromanomr** [inspace-io/INSPhotoGallery#32]
Version 1.2 is crashing in Xcode 9 using swift 3.2. Aversion 1.1.0 was working normally

**Comment by m1entus** [comment]
You mean not compiling ? I add if check for swift 4.0/3.2 and added 1.2.1 version, could you check it now ?

**Comment by lucasromanomr** [comment]
Both the project and pod are set to swift 3.2.
Following is the two problems that are emerging.

`INSPhotosOverlayView.swift`

<img width="1187" alt="captura de tela 2017-09-21 as 12 51 35" src="https://user-images.githubusercontent.com/3859282/30705423-cd7ecea0-9ecb-11e7-9fdb-70614a3cb728.png">

`INSPhotosViewController.swift` 

<img width="1150" alt="captura de tela 2017-09-21 as 12 51 53" src="https://user-images.githubusercontent.com/3859282/30705435-d5090d8e-9ecb-11e7-9582-df5e75dc3649.png">

**Comment by m1entus** [comment]
Check 1.2.1, i have updated it

**Comment by diegomazzone** [comment]
@m1entus same error here (can't compile) with latest version 1.2.1.

**Comment by diegomazzone** [comment]
I think it's fixed for swift 4 but no for swift 3.2

**Comment by m1entus** [comment]
Finally should be fixed.
