### ISSUE TITLE
Swift 4: Apple Mach-O Linker (id) Warning

### ISSUE THREAD

**Issue by seenoevo** [inspace-io/INSPhotoGallery#33]
I'm receiving the following warning in regards to INSNibLoading.framework

![untitled](https://user-images.githubusercontent.com/8109158/30846926-5ff3cfda-a24e-11e7-86a4-0b8e2ebf67f6.png)

I know it's just a warning but any way this can be fixed?

**Comment by m1entus** [comment]
Use cocoapods or Buld Active Architecture Only to NO in plist
