### ISSUE TITLE
INSPhotosViewController datasource public?

### ISSUE THREAD

**Issue by CodingSam** [inspace-io/INSPhotoGallery#34]
How can I read the INSPhotosViewControllers datasource, im just getting error: 
    ```'dataSource' is inaccessible due to 'internal' protection level```

If I change ```private(set) var dataSource: INSPhotosDataSource``` to ```public var dataSource: INSPhotosDataSource``` in ```INSPhotosViewController.swift``` it works correctly.

Is there a reason why it is private or can I submit a PR where it is fixed? Or is there another way to read it?

**Comment by m1entus** [comment]
Submit PR,

**Comment by CodingSam** [comment]
https://github.com/inspace-io/INSPhotoGallery/pull/35

**Comment by m1entus** [comment]
Sorry, i understood that you want to change it to private(set), this shouldn't be public because of encapsulation

**Comment by CodingSam** [comment]
How can I then access the datasource? I need it to show the "image index" in the overlay. @m1entus

**Comment by m1entus** [comment]
This should be just `public private(set) var photos: [INSPhotoViewable] = []`

**Comment by CodingSam** [comment]
In the examples you get the index like this:
```
func populateWithPhoto(_ photo: INSPhotoViewable) {
    self.currentPhoto = photo
        
    if let photosViewController = self.photosViewController {
            
        if let index = photosViewController.dataSource.indexOfPhoto(photo) {
            self.navigationItem.title = "\(index+1) / \(photosViewController.dataSource.numberOfPhotos)"
        }
            
        self.captionLabel.attributedText = photo.attributedTitle
    }
}
```

But now the datasource is private. And I get the ```'dataSource' is inaccessible due to 'internal' protection level```error.

**Comment by m1entus** [comment]
Doing `public private(set)` only setter is private, and getter is public

**Comment by CodingSam** [comment]
Alright, so you want me to do a PR with that change @m1entus ? ```private(set)``` -> ```public private(set)```

**Comment by m1entus** [comment]
It is already done

**Comment by CodingSam** [comment]
Yes I can see that you changed it in the datasource, but how do I access the datasource? I have a custom overlay where I need to access it.

**Comment by m1entus** [comment]
Ok, i have opened some fields
