### ISSUE TITLE
Unable to change title

### ISSUE THREAD

**Issue by sinarionn** [inspace-io/INSPhotoGallery#38]
What is correct way to change title (i don't want to show "1 of 1")?
I can not modify overlay's navigationItem.title because it will be overwritten by "populateWithPhoto" in the future.
I thought i can override "populateWithPhoto" on INSPhotosOverlayView but for this you need to make it's constructor init(frame: CGRect) public.

**Comment by m1entus** [comment]
Feel free to make PR with public constructor

**Comment by sinarionn** [comment]
I found workaround for my issue and you can fix init visibility later. 
Also you will probably need to replace:
`if let bundlePath = Bundle(for: type(of: self)).path(forResource: "INSPhotoGallery", ofType: "bundle")`
with
`if let bundlePath = Bundle(for: BundleAnchor.self).path(forResource: "INSPhotoGallery", ofType: "bundle")`
i think this is a better way, because your version will fail in case if 'self' - user's own inherited class

P.S. BundleAnchor is simple private class: 
`private class BundleAnchor {}`

**Comment by m1entus** [comment]
I have added public init(frame: CGRect) in #4a593e4
