### ISSUE TITLE
Crash when saving picture

### ISSUE THREAD

**Issue by MelanieJourne** [inspace-io/INSPhotoGallery#41]
Hello,

When I try to save a photo with the action in the right item button, the application crash because I don't have gallery right.

I test it on an iPhoneX and 7, both on iOS11 and i got the crash.
I test it on an iPhone6 on iOS10.3 and no problem.

Is it a know iOS11 issue ? Will it be fixed soon ?

Thanks you so much for your help

**Comment by m1entus** [comment]
Please paste the crashlog or example to reproduce it, or tell me how to do it

**Comment by MelanieJourne** [comment]
Hello,

I found my problem, I was missing this key in my Info.plist : 
<key>NSPhotoLibraryAddUsageDescription</key>
And iOS11 absolutely need it or it will crash.

Hope it can help people with the same problem as me.
