### ISSUE TITLE
Can I update background color of INSScalingImageView ?

### ISSUE THREAD

**Issue by dproton** [inspace-io/INSPhotoGallery#43]
Currently, INSScalingImageView is declared as internal level and I can't get it ? Can you public it ? Thank you so much

**Comment by m1entus** [comment]
Why you want to get access to it ?

**Comment by dproton** [comment]
Thanks for your response,
Some images I got from server is transparent background, and INSScalingImageView.backgroundColor == .clear, so the image can't be display

The current one:
![simulator screen shot - iphone 6s - 2018-04-10 at 16 06 51](https://user-images.githubusercontent.com/8925426/38547441-49a6bc44-3cd9-11e8-9b17-74645b28a1a1.png)

My expectation (and I can do it if I can set INSScalingImageView.backgroundColor)

<img width="485" alt="screen shot 2018-04-10 at 16 07 19" src="https://user-images.githubusercontent.com/8925426/38547440-4958131e-3cd9-11e8-9cc8-267183f19633.png">

**Comment by m1entus** [comment]
You can subclass and override func initializePhotoViewControllerForPhoto(_ photo: INSPhotoViewable) -> INSPhotoViewController method and INSPhotoViewController have lazy private(set) var scallingImageView property, and then you can set background

**Comment by dproton** [comment]
But currently, INSPhotosViewController is only public and can't be inherited

**Comment by m1entus** [comment]
Can you open it and create PR ?
