### ISSUE TITLE
Update property declaration in protocol

### ISSUE THREAD

**Issue by seenoevo** [inspace-io/INSPhotoGallery#46]
Using Swift 4.1 with the latest Xcode and getting a warning in `INSPhotosOverlayView.swift`:
![untitled](https://user-images.githubusercontent.com/8109158/38603979-f25f9348-3d23-11e8-9c5c-c254c25bda25.png)

Removing the keyword `weak` resolves the warning.

I know it's just a simple warning, but can you update this?...I prefer not to touch the source code.

Thanks.

**Comment by m1entus** [comment]
fixed
