### ISSUE TITLE
is there kind of support of SDWebImage?

### ISSUE THREAD

**Issue by bizibizi** [inspace-io/INSPhotoGallery#48]
I want to display items which already cached with SDWebImage without downloading them again

**Comment by pduvall** [comment]
I have accomplished this by first preparing an array of gallery images that contains INSPhoto objects that are instantiated with the URLs of the images. Here is some example code from my project that you may be able to modify to suit your needs:

```
var galleryImages = [INSPhotoViewable]()

for additionalImage in additionalImages {
            
    if let imageUrlString = additionalImage.imageURL, let imageUrl = URL(string: imageUrlString) {
        galleryImages.append(INSPhoto(imageURL: imageUrl, thumbnailImageURL: imageUrl))
    }
}
```

Then when I asynchronously load an image with SDWebImage, I change the INSPhoto object in the galleryImages array to one that is instantiated with the image data that has just been received: (note that this asynchronous call will finish very quickly if the image is already cached, so it should be in the array before the user launches the full screen gallery view)
```
imageView.sd_setImage(with: imageURL, completed: { (image, _, _, _) in
                
    if let image = image {
        self.galleryImages[indexPath.item] = INSPhoto(image: image, thumbnailImage: image)
    }
})
```
