### ISSUE TITLE
How to dismiss the controller with the tap on the photo?

### ISSUE THREAD

**Issue by cristinaITdeveloper** [inspace-io/INSPhotoGallery#51]
I would like to dismiss the gallery by tapping on the photo and not with the drag.
How can I do?
Here my code:
    
        func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        
        let cell : PhotoCollectionViewCell = collectionView.cellForItem(at: indexPath) as! PhotoCollectionViewCell
        
        let currentPhoto = photos[indexPath.row]
        
        galleryPreview = INSPhotosViewController(photos: photos, initialPhoto: currentPhoto, referenceView: cell)
        galleryPreview.defaultOverLayViewCanHaveNavigationBar = false
        galleryPreview.referenceViewForPhotoWhenDismissingHandler = { [weak self] photo in
            if let index = self?.photos.index(where: {$0 === photo}) {
                let indexPath = IndexPath(item: index, section: 0)
                return collectionView.cellForItem(at: indexPath) as? PhotoCollectionViewCell
            }
            return nil
        }
        present(galleryPreview, animated: true) {
        
        }
    }

Thank you!

**Comment by m1entus** [comment]
You can try attach tap gesture to your custom INSPhotosOverlayView
