### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by TwunTee** [inspace-io/INSPhotoGallery#53]
Hi can you add carthage support, i am getting error that there are no shared frameworks, the pull request https://github.com/inspace-io/INSPhotoGallery/pull/42 seems to have added the shared framework to the example instead of the library, not sure if that is what it is intended for

**Comment by m1entus** [comment]
PR welcome

**Comment by vdeep** [comment]
PR sent.
https://github.com/inspace-io/INSPhotoGallery/pull/56
