### ISSUE TITLE
How Import INSNibLoading?

### ISSUE THREAD

**Issue by saeedmozaffariGithub** [inspace-io/INSPhotoGallery#57]
Hi, 
I want to make custom overlay, but i can't import 'INSNibLoading' so i can't use from 'INSNibLoadedView'. How Import INSNibLoading?

Hint: i don't use from pod!

**Comment by saeedrooyekhat** [comment]
i added INSNibLoading framework from [here](https://github.com/akamai/UrbanCrawl-iOS/tree/master/DerivedData/UrbanCrawl/Build/Products/Debug-iphonesimulator/INSNibLoading/INSNibLoading.framework)

**Comment by m1entus** [comment]
https://github.com/inspace-io/INSNibLoading
