### ISSUE TITLE
Crash when actionButtonTapped is tapped in iPad

### ISSUE THREAD

**Issue by mperezrojas** [inspace-io/INSPhotoGallery#6]
When you are in the gallery in iPad and you tap the share barbutton the app crash, I think it is because in ipad is necesary show the ActivityController like a popover

**Comment by haithngnbak** [comment]
@thefronter ,
I meet same problem with you,
You could try replace this methd: actionButtonTapped in this file INSPhotosOverlayViewable.Swift

by this code 

> @objc private func actionButtonTapped(sender: UIBarButtonItem) {
>         if let currentPhoto = currentPhoto {
>             currentPhoto.loadImageWithCompletionHandler({ [weak self](image, error) -> () in
>                 if let image = (image ?? currentPhoto.thumbnailImage) {
>                     if (UI_USER_INTERFACE_IDIOM() == .Phone) {
>                         let activityController = UIActivityViewController(activityItems: [image], applicationActivities: nil)
>                         self?.photosViewController?.presentViewController(activityController, animated: true, completion: nil)
>                     } else {
>                         let activityController = UIActivityViewController(activityItems: [image], applicationActivities: nil)
>                         let popup:UIPopoverController = UIPopoverController(contentViewController: activityController)
>                         popup.presentPopoverFromRect(CGRectMake(self!.view().frame.size.width - 36, 36, 0, 0),
>                             inView: (self?.view())!, permittedArrowDirections: .Any, animated: true)
>                     }

```
            }
        });
    }
}
```

it worked for me
![simulator screen shot aug 17 2016 10 55 45 pm](https://cloud.githubusercontent.com/assets/1132303/17743400/d02173c6-64cd-11e6-9b20-f193bf35f905.png)

**Comment by m1entus** [comment]
Fixed.
