### ISSUE TITLE
Is there a way to show and hide status bar with custom or default layout?

### ISSUE THREAD

**Issue by vkhadyka** [inspace-io/INSPhotoGallery#66]
Hi. I've tried a few way but it haven't successfully. I wanna display/hide status bar with custom or default overlay with the same animation as layout. How can I achieve it?

**Comment by KPR7168** [comment]
I faced similar issue. What I did was create a subclass of `INSPhotosViewController` then create a field say `shouldHideStatusBar` as `Bool` and override `prefersStatusBarHidden` and return `shouldHideStatusBar`.

Then in your customer overlay view, in `setHidden(_ hidden: Bool, animated: Bool)` listen to `hidden` and set `shouldHideStatusBar` accordingly. Finally call `setNeedsStatusBarAppearanceUpdate()` in your subclass.
