### ISSUE TITLE
Localization workaround for photo index text

### ISSUE THREAD

**Issue by vidriloco** [inspace-io/INSPhotoGallery#8]
On the class **INSPhotosOverlayView** the function name _populateWithPhoto_ is in charge of setting the texts on each one of the controllers which are related to the pictures the gallery displays. On that function, the heading text is set, but it is set using an english connector, namely "of". 

For apps which need to be localized, this is no handy.  Thus, the simplest workaround would be to change the "1 of n" to "1 / n" instead. A more elaborated solution would be to use a localized string which might be more desirable. Another option would be to provide a parameter on the gallery initialization for customizing this string.

**Comment by m1entus** [comment]
Fixed.
